# Docker-compose file for spinning up a local MySQL database.

version: "3"
services:
  database:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: fearless
      MYSQL_DATABASE: purplecowapp